### PR TITLE
Use ReactModal for PostModal

### LINKED ISSUE #1331: Add post modal

### PR DESCRIPTION
**Pull request by jm90m**
In an effort to figure out how to optimize the performance of this post modal, specifically with posts that have large comments `/dlive/@dlive/dlive-0-2-0-ui-now-optimized-for-mobile`.. I decided to try it out using ReactModal as well..

Let me know what you guys think is faster / better to use?

Fixes #1331

Changes:
- Use ReactModal instead of antd Modal

### CODE REVIEW

**Comment by bonustrack** [comment]
On mobile it doesnt render well. Can you try on mobile and tell which method is faster? It feel similar speed at first glance too me

**Comment by jm90m** [comment]
oh yeah I still need to update styles manually for mobile... forgot about that was just testing specifically for comments being rendered @bonustrack

**Comment by Sekhmet** [comment]
It might get better after implementing #1413

**Comment by bonustrack** [comment]
- The modal is not properly centered
- We should start from the top of the scroll
- There is a left margin on mobile we should remove that:
image

Do you feel it's better or faster than #1376 @Sekhmet @jm90m ?

**Comment by jm90m** [comment]
@bonustrack I didn't do much styling on this, you have to manually do all the styles if you use ReactModal.. So I still need to do the mobile styles as well..

But I'm hoping @Sekhmet comment updates (https://github.com/busyorg/busy/issues/1413), can make it render faster.

Only was testing to see if ReactModal was faster than antd with comments for posts like the latest post on here: https://busy-master-pr-1444.herokuapp.com/@dlive

To me they both feel the same, depending on content

**Comment by jm90m** [comment]
Closing this, will use antd modal.

**Pull request closed without merging**
