### PR TITLE
Show voting power bar in comments if enabled for user

### PR DESCRIPTION
**Pull request by blueyedgeek**
### What does this PR do?

Adds voting power slider to user comments on a post

### Relevant trello link

https://trello.com/c/N5oZYBHo/6-voting-power-slider-on-comment

### CODE REVIEW

**Comment by blueyedgeek** [comment]
@bonustrack on what page(s) does this occur?

**Comment by bonustrack** [comment]
It's really hard to not having the voting slider disappear when trying to move it see:
slider
This behavior is only in comment like sliders, not in root post like sliders. The implementation should be same.

**Comment by blueyedgeek** [comment]
@bonustrack, the issue has been addressed, can you check again?

**Comment by bonustrack** [comment]
@blueyedgeek looking better now.

**Pull request merged**
