### PR TITLE
feat(client): start implementing sticky-sidebar

### LINKED ISSUE #1515: Sidebar in the post jumps to the top of the page
#### Expected behavior
The sidebar in the post should remain fixed on the right, visible to the user.

#### Actual behavior
If you open a post with a sidebar that is higher than the window (you must scroll to see full content), it may disappear / jump to the top of the page while scrolling up within the post.

ezgif com-video-to-gif

ezgif com-video-to-gif 2

#### How to reproduce
1. Open a post in staging.busy.org (https://staging.busy.org/@justyy/utopian-chrome-extension-v0-0-9-integrate-stats-api-add-node-list)
2. Make sure that the sidebar does not fit the window (You can resize the window)
3. Scroll down to toggle the comment section so that there is enough space to scroll up
4. Scroll up / Scroll down

* Browser: Google Chrome 64.0.3282.140
* Operating system: Windows 10

### Additional recordings

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@espoem/sidebar-in-the-post-jumps-to-the-top-of-the-page">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

### PR DESCRIPTION
**Pull request by Sekhmet**
This is just there to make changes public. It's nowhere close to being ready to merge (CI will fail).

I started reimplementing Affixes using `sticky-sidebar`. Had to rewrite layouts using flexbox to make it work properly (not ready yet). However, there is a problem with hero banner. If it's present it overlaps it. I have to still figure this out.

Fixes #1515

### CODE REVIEW

**Comment by bonustrack** [comment]
@Sekhmet wassup about this thing?

**Comment by Sekhmet** [comment]
It is just a rewrite to use the external library instead of Affixes, but it has its own problems, that are not trivial to solve.

**Comment by bonustrack** [comment]
Is it something you plan to solve anytime soon @Sekhmet ? Should we keep this PR open?

**Comment by Sekhmet** [comment]
This library doesn't handle every edge case we might want to handle, so I will close this PR as there is no point in implementing this.

**Pull request closed without merging**
