### PR TITLE
Fix "Edit option below a comment is not fully visible on mobile"

### LINKED ISSUE #1036: Edit option below a comment is not fully visible on mobile
#### Expected behavior

All elements and text in the line below a comment should be fully visible.

screenshot_20171107-070343

#### Actual behavior

The edit word in Czech "Upravit" is partly cut off if the comment is not at the top level of comment conversation.

screenshot_20171107-070331

#### How to reproduce

1. Set language to Czech
2. Find your comment that is not at the top level

* Browser: Brave
* Operating system: Android 7.1.2

### PR DESCRIPTION
**Pull request by jedau**
Fixes #1036 

Problem was that string overflow was clipped. Several solutions were tested using `word-wrap` but ended up with varying results. Final solution keeps it simple by dividing the comment footer into two halves and placing a line break in between them. No matter the length of the strings, they won't be clipped. However, the bullet that separated the payout amount and the reply link had to be removed.

Changes:
- src/client/components/CommentFooter/Buttons.js

### CODE REVIEW

**Comment by jm90m** [comment]
This looks to be the same as `https://github.com/busyorg/busy/pull/1159` just different solutions, when we have time, @Sekhmet, @bonustrack, or me, will see which solution is better based on code quality / design.

**Comment by jedau** [comment]
@jm90m oh yeah, I did see that just as I was about to make a pull request. When I examined it, the output did look similar, but the approach was quite different. I still submitted because I spent quite some time thinking of the fix. With all due respect to sweever, as I see that his solution was very well thought of, I feel like my more simple approach works without disrupting the flow too much. Initially, I was going for a more complicated solution as well, but I opted for a more simple one instead.

I've been wanting to get involved with Busy for quite some time now, but I wanted to get my feet wet first with easier bugs to get acclimated. Whichever you guys choose, I'm cool with it. Thanks for the consideration, man!

**Comment by jm90m** [comment]
@jedau thanks for the contribution and the time spent, means a lot, me, @bonustrack and @Sekhmet will analyze both PRs and see which one is better. :)

**Comment by jedau** [comment]
@jm90m happy to help! :D Looking forward to making more contributions in the coming weeks.

**Comment by jm90m** [comment]
idk if this PR works, it doesn't look to be working for me

https://busy-master-pr-1166.herokuapp.com/test/@hellosteem/2ttwm2-test

screen shot 2017-12-12 at 11 53 01 am

can you take a screenshot of what you see? thanks

**Comment by jedau** [comment]
Hey @jm90m sorry for getting back so late. I'm not quite sure why it's not working. The link you included is down for me, so I'm not able to investigate from there. The only thing I did for this PR was to separate the two halves of the comment footer into separate divs and added a line break between them. Is that not what's appearing for you?

**Comment by jm90m** [comment]
@jedau nope it doesn't appear as so, in the screenshot.

**Comment by jm90m** [comment]
@jedau  this doesn't work for you? https://busy-master-pr-1166.herokuapp.com/

**Comment by jedau** [comment]
@jm90m the link's working for me know but I can't seem to log in. I wonder why my fix isn't working for you though. It was basically just a line break added in it.

**Comment by jm90m** [comment]
@jedau to login to a PR build of the app you have to stop running your local dev of busy, then when you click login you should see the following url at the top `http://localhost:3000/callback?access_token=abcdefg&expires_in=604800&username=yourusername`

Now what you want to do is take the following: `/callback?access_token=abcdefg&expires_in=604800&username=yourusername`

and add it along to the PR heroku app build so you add it like this `https://busy-master-pr-1166.herokuapp.com/callback?access_token=abcdefg&expires_in=604800&username=yourusername`

And you put that link into your browser, go to it, and you should now be logged in

**Comment by jedau** [comment]
@jm90m hey man, tried the login out, and it worked like a charm. I inspected the code and it doesn't seem that my changes were reflected there. I wonder why that is. Did I miss something in terms of committing? You do see my files changed in the PR, right? Definitely weird. Here's a look of that section in my dev-server:

dev-server

As you can see, there are two `div`s inside the larger (original) `div`.

And this is from the PR:

dev-server

So, this is how it looks while running my dev-server:

dev

This was just a simple fix, I'm sorry for all the hoops just to get to this, man.

**Comment by jm90m** [comment]
@jedau to be honest, I am not sure why its not getting reflected.. this hasn't happened to us before, when I have time I can look into it but idk. Anyways can you screen shot what the result would look like in different languages / screen sizes? @bonustrack has the final say on the design, and he can assess if your fix is good from a design standpoint

**Comment by jedau** [comment]
@jm90m here you go, man:

fullcs
(Full Screen - Czech)

smallcs
(Small Screen - Czech)

fullsp
(Full Screen - Spanish)

smallsp
(Small Screen - Spanish)

Also, is there an easy way to change the locale? What I did was to change the browser's language. I hope we figure out why the fix isn't being implemented :)

**Comment by jm90m** [comment]
thanks @jedau, I'll let @bonustrack our CTO make the final call on this design

**Comment by jedau** [comment]
@jm90m thanks, man! I appreciate the very active communication about this :)

Whatever the decision, it's great to be involved. Happy to be shaking off some coding rust haha! I've been trying to find other bugs to raise.

**Comment by bonustrack** [comment]
I don't think its good solution to have comment actions in 2 lines, it make every comment taking more space vertically even on large screen, while there wasn't any issue on large screen.

**Comment by bonustrack** [comment]
I'm closing this PR, i dont think it's the right way to fix with issue.

**Comment by jedau** [comment]
@bonustrack oh alright, you're the boss. It was worth a shot :)
@jm90m thanks for the back and forth, man. I appreciate it :)

**Pull request closed without merging**
