### PR TITLE
Add Sort By Author Reputation

### LINKED ISSUE #1606: Sort comment by author reputation
https://busy.org/@therealwolf/feature-request-sorting-comments-by-author-reputation

### PR DESCRIPTION
**Pull request by caleblogan**
Fixes #1606

Changes:
- Add sort by author reputation to comments

### CODE REVIEW

**Comment by bonustrack** [comment]
Thank you for your contribution, that was fast :). Are you Busy Discord user?

**Comment by bonustrack** [comment]
Sorting by reputation seem to working well for root comments but not for nested, can you make it work for nested comments too?
image

**Comment by caleblogan** [comment]
@bonustrack Yeah, I'm in a few of the steem discord channels. I think I used the same name as steem, okc.

**Comment by caleblogan** [comment]
I think its a bug with the overall sorting implementation. When sorting changes, sub level comments don't receive the new sort key. They all have the `BEST` default sort param set. Should I create a another pr to fix that issue or do it here?

**Comment by bonustrack** [comment]
@caleblogan ok yes, this can fit into another PR.

**Pull request merged**
