### PR TITLE
Fix failing tests busy1

### PR DESCRIPTION
**Pull request by blueyedgeek**
### What does this PR do

It fixes all failing tests on the project so that continuous integration with `circle ci` works smoothly

### Relevant `trello` board

https://trello.com/c/GXw7OIe3/4-fix-test

### CODE REVIEW

**Comment by Sekhmet** [comment]
I encounter weird error when running `test` script on my local machine.
```zsh
➜  busy git:(fix-failing-tests-busy1) yarn run test   
yarn run v0.27.5
$ cross-env BUSYWS_HOST=https://ws.busy.org BABEL_ENV=test && mocha -r babel-register -r ignore-styles ./src/**/*.spec.js
Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
loc undefined
/home/sekhmet/Workspace/busy/node_modules/socket.io-client/lib/url.js:29
  if (null == uri) uri = loc.protocol + '//' + loc.host;
                            ^

TypeError: Cannot read property 'protocol' of undefined
    at url (/home/sekhmet/Workspace/busy/node_modules/socket.io-client/lib/url.js:29:29)
    at Function.lookup [as connect] (/home/sekhmet/Workspace/busy/node_modules/socket.io-client/lib/index.js:44:16)
    at new MessagesWorker (/home/sekhmet/Workspace/busy/src/messages/messagesBackground.js:37:22)
    at Object.<anonymous> (/home/sekhmet/Workspace/busy/src/store.js:15:31)
    at Module._compile (module.js:570:32)
    at loader (/home/sekhmet/Workspace/busy/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/sekhmet/Workspace/busy/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/sekhmet/Workspace/busy/src/helpers/actionDecorator.spec.js:11:1)
    at Module._compile (module.js:570:32)
    at loader (/home/sekhmet/Workspace/busy/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/sekhmet/Workspace/busy/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /home/sekhmet/Workspace/busy/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/sekhmet/Workspace/busy/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/home/sekhmet/Workspace/busy/node_modules/mocha/lib/mocha.js:495:10)
    at Object.<anonymous> (/home/sekhmet/Workspace/busy/node_modules/mocha/bin/_mocha:469:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Machine**: Linux 4.10.0-30-generic ~16.04.1-Ubuntu SMP Wed Aug 2 02:13:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
**Node**: v6.11.1, v6.10.3 or v8.2.1
**Package manager**: npm@3.10.10 or yarn@0.27.5

This might be device specific, I cleaned `node_modules` everytime and this issue doesn't seem to solve itself. I encountered this problem before when trying to fix tests myself. No luck finding solution for this.

**Comment by bonustrack** [comment]
I'm having the same issue in local, unless i change `process.env.BUSYWS_HOST` to plain text `'https://ws.busy.org'` here: https://github.com/busyorg/busy/blob/83c3618865b003a8f7c57d8cb798d5d8143e183e/src/messages/messagesBackground.js#L37
It seem that the config var `BUSYWS_HOST` is not properly set, it return undefined on local.

**Comment by Sekhmet** [comment]
Thing is that it's part of client side code, thus it doesn't have access to `process.env`. We use `webpack.DefinePlugin` to supply environment variables to client code, but mocha doesn't use webpack, so it doesn't receive them.

**Comment by Sekhmet** [comment]
Problem is that we are using `cross-env BUSYWS_HOST=https://ws.busy.org BABEL_ENV=test && mocha` instead of `cross-env BUSYWS_HOST=https://ws.busy.org BABEL_ENV=test mocha` (note missing `&&`. Because of that mocha doesn't have access to env variables.

**Pull request merged**
