### PR TITLE
Use lodash get in parser.js to fix post breaking

### LINKED ISSUE #1758: Blank page for single post on staging
Single post page is giving a blank page:
https://staging.busy.org/@roxane/ta-dose-quotidienne-de-motivation-pour-devenir-un-steemien-a-succes-22
image
Do we know which PR caused this issue?

### PR DESCRIPTION
**Pull request by jm90m**
Fixes #1758.

Changes:
- Use lodash _.get instead of directly calling the array property

### CODE REVIEW

**Comment by Sekhmet** [comment]
Hey, actually there is a problem with the way links are parsed with Regex. I will send you a diff in a moment that solves that.

**Comment by Sekhmet** [comment]
```diff
diff --git a/src/client/helpers/parser.js b/src/client/helpers/parser.js
index c1c0453..8e53756 100644
--- a/src/client/helpers/parser.js
+++ b/src/client/helpers/parser.js
@@ -7,7 +7,8 @@ export function getFromMetadata(jsonMetadata, key) {
   return _.get(metadata, key);
 }
 
-const attr = /(\w+)="(.*?)"/;
+const attrs = /(\w+=".*?")/g;
+const attrElements = /^(\w+)="(.*?)"$/;
 const imgTag = /<img(.*)\/>/g;
 const hrefRegex = /<a[^>]+href="([^">]+)"/g;
 
@@ -24,17 +25,20 @@ function extract(body, regex) {
 }
 
 export function extractImageTags(body) {
-  const imageTags = extract(body, imgTag);
+  return extract(body, imgTag).map(image => {
+    const attributes = image.match(attrs);
 
-  return imageTags.map(image => {
-    const pairs = image.trim().split(' ');
+    return attributes.reduce((a, b) => {
+      const values = b.match(attrElements);
 
-    return pairs.reduce((a, b) => {
-      const matches = b.match(attr);
-      return {
-        ...a,
-        [matches[1]]: matches[2],
-      };
+      if (values.length === 3) {
+        return {
+          ...a,
+          [values[1]]: values[2],
+        };
+      }
+
+      return a;
     }, {});
   });
 }

```

**Comment by jm90m** [comment]
thanks @Sekhmet

**Comment by jm90m** [comment]
Also fixes #1772

**Pull request merged**
