### PR TITLE
Set left and right margins to 0 for .Body pre; set width to 96%

### LINKED ISSUE #771: Bug display Code in comments
commentbug

### PR DESCRIPTION
**Pull request by eastmaels**
fixes #771

### CODE REVIEW

**Comment by Sekhmet** [comment]
Thanks for contributing.
Looks like this still overflows on smaller screens:
image
We should find a way to make this work well on different screen sizes.

You don't have to create new pull request. If you push new commits to this branch they will be added to this pull request as well.

**Comment by eastmaels** [comment]
ok. thanks. will look into it.

**Comment by Sekhmet** [comment]
I'm not even close to CSS expert so I'm not sure how useful this will be, but I noticed that if there is `white-space: normal` on `pre` or `code` element it renders properly (meaning it renders width as should but it removes scrollbars which is not what we want). Not sure if it's any useful, but it might help.

**Comment by jm90m** [comment]
Hi, thanks for contributing!

So a deeper issue is that the width of the entire comment container itself is overlapping the right sidebar. Might be good to look towards fixing that first and the rest should be fixed.
screen shot 2017-10-14 at 1 11 06 pm

**Comment by Sekhmet** [comment]
It is only the case if there is `pre>code` inside. If it's not it has proper width.

**Comment by eastmaels** [comment]
Yes, based on my observation, this is caused by the `pre > code` blocks adding margins to the whole element so I tried removing the margins and shrinking the width.

image

Compared to that which does not contain a `pre > code`

image

**Comment by jm90m** [comment]
Hello,

So I've been thinking about this one a lot, I think a better solution would be to wrap the text like so: https://github.com/busyorg/busy/pull/834

Rather than set a width. This fix should work well with responsive design.

**Comment by bonustrack** [comment]
I'm closing this PR, the issue has been fixed here #834

**Comment by eastmaels** [comment]
Nice workaround @jm90m . Thanks.

**Pull request closed without merging**
