### PR TITLE
Use markdown-it

### LINKED ISSUE #1945: Markdown is processed incorrectly
#### Actual behavior

Markdown is not processed as it should be.

image

image

#### How to reproduce

1. See https://busy.org/@espoem/growing-the-potential-audience-of-video-content or https://busy.org/@lemouth/particle-physics-utopian-implementing-an-lhc-analysis-on-a-computer-the-physics-objects

* Browser: Chrome 66
* Operating system: Windows 10

### PR DESCRIPTION
**Pull request by Sekhmet**
Fixes #1945 

### Changes

* Use markdown-it (up-to-date remarkable).

This ignores #1647, as it's not a bug, but not correct Markdown.
See spec: https://spec.commonmark.org/0.28/#html-blocks

### Test plan

* [X] This post should render properly: https://busy-master-pr-1961.herokuapp.com/@espoem/growing-the-potential-audience-of-video-content

### CODE REVIEW

**Comment by quochuy** [comment]
My posts still don't render properly, check the bottom of this:
https://busy-master-pr-1961.herokuapp.com/@quochuy/witness-update-2018-06-07-steem-communities-and-eos-witnessing

It does render properly on steemit.com:
https://steemit.com/witness-category/@quochuy/witness-update-2018-06-07-steem-communities-and-eos-witnessing

**Comment by Sekhmet** [comment]
It's not correct markdown, so it might not render properly.

**Comment by bonustrack** [comment]
Spotted some issue here: https://busy-master-pr-1961.herokuapp.com/@luzcypher/steemit-open-mic-week-88-winners-see-who-won-open-mic-and-join-us-this-week while its working on steemit
image 
image

**Comment by Sekhmet** [comment]
@bonustrack 

image

image

It works on Steemit sometimes, because of some undefined behaviour, it can as well not work:
https://steemit.com/test/@hellosteem/ms3nz-test

**Pull request merged**
