### PR TITLE
Update webpack and related dependencies.

### PR DESCRIPTION
**Pull request by Ne3l**
Previously try #616 seems to had some style issues. After some testing i haven't been able to find any issue but another check by other member would be nice.

### CODE REVIEW

**Comment by bonustrack** [comment]
Thank you for your PR! Look like CircleCi test are failing can you try to update test using the command `npm test -- -u` ?

**Comment by bonustrack** [comment]
Did you tried `ModuleConcatenationPlugin`? See "Scope Hoisting" in https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b

**Comment by Ne3l** [comment]
`npm test -- -u` works fine locally.

**Comment by Sekhmet** [comment]
Did you add all files to commit after running `npm test -- -u`?

**Comment by Ne3l** [comment]
git status didn't report any file to add/commit after `npm test -- -u`

**Comment by Sekhmet** [comment]
It fails on when working on code-coverage (it passess tests alone though)
```sh
#!/bin/bash -eo pipefail
npm run test:coverage
npm info it worked if it ends with ok
npm info using npm@5.3.0
npm info using node@v8.4.0
npm info lifecycle busy@2.0.0~pretest:coverage: busy@2.0.0
npm info lifecycle busy@2.0.0~test:coverage: busy@2.0.0

> busy@2.0.0 test:coverage /home/circleci/busy
> cross-env IMG_HOST=https://img.busy.org jest --coverage

 PASS  src/wallet/__tests__/walletActions.js
 PASS  src/wallet/__tests__/walletReducer.js
 FAIL  src/replies/__tests__/Replies.js
  ● Test suite failed to run

    /home/circleci/busy/src/replies/Replies.js: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
      
      at NodePath.insertBefore (node_modules/babel-traverse/lib/path/modification.js:61:13)
      at VisitState.insertCounter (node_modules/istanbul-lib-instrument/dist/visitor.js:197:22)
      at VisitState.insertStatementCounter (node_modules/istanbul-lib-instrument/dist/visitor.js:224:18)
      at VisitState.coverStatement (node_modules/istanbul-lib-instrument/dist/visitor.js:340:10)
      at node_modules/istanbul-lib-instrument/dist/visitor.js:327:15
          at Array.forEach (<anonymous>)
      at VisitState.wrappedEntry (node_modules/istanbul-lib-instrument/dist/visitor.js:326:15)
      at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)
      at NodePath.call (node_modules/babel-traverse/lib/path/context.js:48:17)
      at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:105:12)

 PASS  src/comments/__tests__/commentsReducer.js
 PASS  src/auth/__tests__/authReducers.js
 FAIL  src/stories/stories.test.js
  ● Test suite failed to run

    /home/circleci/busy/src/components/Story/PostFeedEmbed.js: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
      
      at NodePath.insertBefore (node_modules/babel-traverse/lib/path/modification.js:61:13)
      at VisitState.insertCounter (node_modules/istanbul-lib-instrument/dist/visitor.js:197:22)
      at VisitState.insertStatementCounter (node_modules/istanbul-lib-instrument/dist/visitor.js:224:18)
      at VisitState.coverStatement (node_modules/istanbul-lib-instrument/dist/visitor.js:340:10)
      at node_modules/istanbul-lib-instrument/dist/visitor.js:327:15
          at Array.forEach (<anonymous>)
      at VisitState.wrappedEntry (node_modules/istanbul-lib-instrument/dist/visitor.js:326:15)
      at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)
      at NodePath.call (node_modules/babel-traverse/lib/path/context.js:48:17)
      at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:105:12)

Test Suites: 2 failed, 4 passed, 6 total
Tests:       17 passed, 17 total
Snapshots:   0 total
Time:        10.162s
Ran all test suites.
--------------------------|----------|----------|----------|----------|----------------|
File                      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
--------------------------|----------|----------|----------|----------|----------------|
All files                 |    33.61 |     6.35 |     4.87 |    37.83 |                |
 .storybook               |       90 |      100 |      100 |    88.89 |                |
  storyshots-setup.js     |       90 |      100 |      100 |    88.89 |             11 |
 src                      |    50.72 |      100 |        0 |    92.11 |                |
  reducers.js             |    50.72 |      100 |        0 |    92.11 |       49,57,71 |
  steemAPI.js             |      100 |      100 |      100 |      100 |                |
 src/app                  |    42.59 |    13.33 |     5.56 |    51.11 |                |
  appActions.js           |       50 |      100 |        0 |       56 |... 37,45,46,50 |
  appReducer.js           |    34.62 |    13.33 |    14.29 |       45 |... 55,61,66,72 |
 src/app/Notification     |       60 |    66.67 |    33.33 |       60 |                |
  notificationActions.js  |       60 |      100 |        0 |       60 |            8,9 |
  notificationReducers.js |       60 |    66.67 |      100 |       60 |            7,8 |
 src/app/Reblog           |    40.54 |    16.67 |       10 |    45.45 |                |
  reblogActions.js        |       36 |        0 |        0 |    39.13 |... 32,34,42,43 |
  reblogReducers.js       |       50 |    33.33 |       25 |       60 |    11,16,25,27 |
 src/auth                 |       58 |       50 |     6.67 |    70.73 |                |
  authActions.js          |    57.14 |        0 |        0 |       64 |... 37,44,52,56 |
  authReducer.js          |    59.09 |       60 |    14.29 |    81.25 |       37,43,48 |
 src/bookmarks            |    43.24 |       20 |     8.33 |       50 |                |
  bookmarksActions.js     |    43.48 |      100 |        0 |       50 |... 33,35,38,47 |
  bookmarksReducer.js     |    42.86 |       20 |       20 |       50 |... 22,25,28,30 |
 src/comments             |     30.1 |      3.7 |     3.45 |    32.29 |                |
  commentsActions.js      |    30.77 |        0 |        0 |    32.79 |... 156,161,162 |
  commentsReducer.js      |    28.95 |     7.41 |     9.09 |    31.43 |... 91,93,96,99 |
 src/favorites            |    63.64 |    16.67 |       25 |       70 |                |
  favoritesActions.js     |      100 |      100 |      100 |      100 |                |
  favoritesReducer.js     |    42.86 |    16.67 |       25 |       50 |... 18,20,28,34 |
 src/feed                 |     26.5 |     1.54 |      3.7 |     28.7 |                |
  feedActions.js          |    33.85 |        0 |        0 |    36.07 |... 216,226,227 |
  feedReducer.js          |    17.31 |     1.96 |     9.09 |    19.15 |... 222,228,233 |
 src/helpers              |    17.69 |        0 |        0 |    19.55 |                |
  apiHelpers.js           |    18.52 |        0 |        0 |       20 |... 106,107,109 |
  formatter.js            |       25 |      100 |        0 |       25 |          2,3,5 |
  metadata.js             |       30 |        0 |        0 |    42.86 |... 32,37,41,48 |
  pushpadHelper.js        |     3.45 |        0 |        0 |     3.45 |... 57,58,59,63 |
  stateHelpers.js         |       20 |        0 |        0 |    22.22 |... 5,96,99,101 |
 src/post                 |    31.15 |     6.06 |     6.25 |    34.55 |                |
  postActions.js          |    40.74 |        0 |        0 |    45.83 |... 48,49,53,54 |
  postsReducer.js         |    23.53 |     8.33 |       10 |    25.81 |... 103,106,119 |
 src/post/Write           |    32.32 |     4.44 |     4.17 |    35.16 |                |
  editorActions.js        |    35.38 |        0 |        0 |     37.1 |... 181,182,185 |
  editorReducer.js        |    26.47 |     9.52 |       10 |    31.03 |... 104,107,111 |
 src/replies              |       40 |        0 |        0 |    43.48 |                |
  repliesActions.js       |       40 |        0 |        0 |    43.48 |... 38,39,41,46 |
 src/user                 |    40.21 |      9.3 |     9.52 |    44.32 |                |
  userActions.js          |    42.37 |        0 |        0 |     46.3 |... 123,126,128 |
  userReducer.js          |    20.83 |    11.76 |    14.29 |    22.73 |... 128,135,140 |
  usersActions.js         |    71.43 |      100 |        0 |    83.33 |              9 |
  usersReducer.js         |    57.14 |    33.33 |       50 |    66.67 |           8,16 |
 src/vendor               |    10.11 |     1.96 |        0 |    10.71 |                |
  responsive.js           |     37.5 |     12.5 |        0 |       40 |... 46,47,55,56 |
  steemitHelpers.js       |     4.11 |        0 |        0 |     4.35 |... 160,161,163 |
 src/vendor/responsive    |       20 |     9.52 |       10 |       20 |                |
  redux-mediaquery.js     |       20 |     9.52 |       10 |       20 |... 87,88,91,94 |
 src/wallet               |    84.62 |      100 |    33.33 |      100 |                |
  walletActions.js        |      100 |      100 |      100 |      100 |                |
  walletReducer.js        |    77.78 |      100 |    33.33 |      100 |                |
--------------------------|----------|----------|----------|----------|----------------|
npm info lifecycle busy@2.0.0~test:coverage: Failed to exec test:coverage script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! busy@2.0.0 test:coverage: `cross-env IMG_HOST=https://img.busy.org jest --coverage`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the busy@2.0.0 test:coverage script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2017-10-24T19_25_55_829Z-debug.log
Exited with code 1
```

**Comment by Sekhmet** [comment]
Does it fail locally when running `npm run test:coverage` as well?

**Comment by Ne3l** [comment]
Works on `npm run test:coverage`. Also tried a fresh reinstall(Deleted node-modules && package-lock.json) and works except some warnings about propTypes.

**Comment by Sekhmet** [comment]
I can reproduce the same error on my machine:
```
Ubuntu 16.04.1 @ 4.10.0-37-generic
npm 5.3.0
node v8.6.0
```

Can you provide us with version of your development tools so I can try to check if it's specific to some version of them?

**Comment by Ne3l** [comment]
`
Windows 10
npm 5.5.1
node v8.5.0
`
This is my development envrionment.

**Pull request merged**
