### PR TITLE
fixes #771; added 50px right margin when comment contains divs

### LINKED ISSUE #771: Bug display Code in comments
commentbug

### PR DESCRIPTION
**Pull request by eastmaels**
fixes #771;

### CODE REVIEW

**Comment by Sekhmet** [comment]
Hey!
Thanks for contributing. I've reviewed this PR and it causes other comments (that don't contain code) to resize as well. Ideally we would render text normally (full-width) making code block match its width, without overflowing.
See: https://busy-dev-pr-786.herokuapp.com/cesky/@xlisto/krmeni-kotat#comments

By the way, you can use `git config --global user.email YOUR_GITHUB_ACCOUNT_EMAIL` so GitHub will connect your commits to your GitHub account.

**Comment by eastmaels** [comment]
Thanks @Sekhmet . i'll limit it more so that it won't affect the length the wrapping of other comments.

**Comment by Sekhmet** [comment]
Work moved to #799

**Comment by eastmaels** [comment]
Thanks

**Pull request closed without merging**
