### PR TITLE
Add ExitPage

### LINKED ISSUE #1492: Add exit page for external links
Hi,

I stumble upon a (minor) security issue that I would like to report you. 

Can you give me a email address to share the informations I have?

### PR DESCRIPTION
**Pull request by Sekhmet**
Fixes #1492

Should be merged after #1629 

### Changes
- [x] Add ExitPage
- [x] Replace external links with ExitPage
- [x] Add icon to external links
- [x] Open exit page on new tab
- [x] Update to use regex from #1631.
- [x] Add go back link.

### Test plan
- [x] Go to post with external URL: https://busy-master-pr-1632.herokuapp.com/@hellosteem/test-links
- [x] External link should have a special icon at the end.
- [x] Clicking on the external link should take the user to exit page.
- [x] Clicking on the `Visit this page` link should open external page.
- [x] Clicking on the back link should take you back to the post.

### Demo

zrzut ekranu 2018-05-07 o 22 55 53
zrzut ekranu 2018-05-07 o 22 56 45

### CODE REVIEW

**Comment by bonustrack** [comment]
What about a modal @Sekhmet ?

**Comment by Sekhmet** [comment]
I'm not a fan of tons of modals opening everywhere, so just made a page for it.
If we open post modal, then we would open yet another modal about leaving Busy (which is not what modals should do).

**Comment by mynameisek** [comment]
something wrong in my opinion @Sekhmet :
a modal would be in fact better for UX since user can accept/refuse to leave, if he refuses, it takes him back to the content he was browsing very easily. I agree with your comment it's not ideal though, we can find something else

at the moment this new exit Page bring user nowhere and let him only one option "Go"
Maybe add a Back button? (GO Url /BACK to the Post) what do you think

**Comment by bonustrack** [comment]
I'm not fan of a multiple modal experience, the exist page could be opened in a new tab. Also it would be great to show an icon for external link like what steemit is doing now:
image

**Comment by Sekhmet** [comment]
@mynameisek I agree that current setup needs an update. It was just demo that we can use to define proper design/UX and implement it.

**Comment by bonustrack** [comment]
@Sekhmet can you
- Resolve conflicts
- Add the similar icon than what steemit is using to external link
- Open external link within a new tab and with the exit page

**Comment by bonustrack** [comment]
@pareshUD do you have a better layout for this exit page: https://busy-master-pr-1632.herokuapp.com/exit?url=https://dlive.io/video/adetorrent/7a4c0d30-3f78-11e8-9b3d-0f0ee12e30d8 ?

**Comment by Sekhmet** [comment]
Can you upload design for this?

cc: @pareshUD

**Comment by pareshUD** [comment]
leaving busy

**Comment by Sekhmet** [comment]
Can you send me this sad face image?

**Comment by bonustrack** [comment]
The user is not really leaving Busy, this is open on a new tab. I think the message is not relevant like that i would no use a sad face aswell for this page. We can talk about it in our next call.

**Comment by bonustrack** [comment]
@Sekhmet 
We will remove the illustration, it's confusing now. Just keep the current integration but make it centered on screen, use bigger button size for "Go back" and change text to:
Title: `Hold on!`
Message: `Be careful, the link may be phishing website. Are you sure you want to go there?` or something between what Wiktor wrote and this. Maybe @jm90m can find something else.

Also can we whitelist steemit.com?

**Pull request merged**
