### PR TITLE
Hide Reblog Icon for own post

### PR DESCRIPTION
**Pull request by jm90m**
* Trello: https://trello.com/c/H9CR4I1q/320-reblog-action-on-my-own-post
* Reblog link is hidden when it is the current user's own post
* When user is not logged in, it redirects to auth page when they click on reblog link

reblog-redirect-auth-busy

### CODE REVIEW

**Comment by Sekhmet** [comment]
Looks good but I don't think that we should add redirect just yet.
I hope to implement this globally with one unified system and add modal with pitch to acquire new users or something like this. There is Trello card for this: https://trello.com/c/i2dwEj9r/91-show-login-signup-modal-for-unlogged-user-who-hit-action-button.

Sorry for confusion. I mentioned login modal to reason why it needed to show reblog icon for unauthenticated user.

**Comment by jm90m** [comment]
@Sekhmet alright should I remove the redirect for now? or did you want me to look into adding the login signup modal?

**Comment by bonustrack** [comment]
Yes @jm90m you can remove the redirection and make https://trello.com/c/i2dwEj9r/91-show-login-signup-modal-for-unlogged-user-who-hit-action-button in another PR

**Comment by jm90m** [comment]
@bonustrack alright I removed passing `isAuthenticated` down and the redirect

**Pull request merged**
