### PR TITLE
Fix #1283 Menu popover 

### LINKED ISSUE #1283: Menu popover still not hidden
#### Expected behavior

**popover** should be hidden after click on one of its items.

#### Actual behavior

**popover** still shown after click on one of its items.

#### How to reproduce

- click on 3dots
- click on one of items

* Browser: Chrome.
* Operating system: Android 6.0

### PR DESCRIPTION
**Pull request by sweever**
Fixes #1283 .

Changes: [src/client/components/Navigation/Topnav.js](https://github.com/busyorg/busy/blob/master/src/client/components/Navigation/Topnav.js)
- delete old methode & put it inside new one when we can handle the event to hide the popover 
- define popover & visible variables that we can take effect on them.
lt783j6zul
uaq8libt2q

### CODE REVIEW

**Comment by sweever** [comment]
@Sekhmet  int work on my **localhost** but i didn't get this error 
`` 34:5  error  propType "onMenuItemClick" is not required, but has no corresponding defaultProp declaration  react/require-default-props``
what does mean ?

**Comment by Sekhmet** [comment]
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/require-default-props.md

**Comment by sweever** [comment]
@Sekhmet this is yours 

> Please make sure you have up-to-date master branch and consider running yarn run prettier and then commit your changes

**Comment by Sekhmet** [comment]
This message tells you everything you need to to know, and even tells you what you can do to fix the issue.
We have strict policy according code formatting. If your code is not formatted properly it will get rejected. You don't have to check it against our servers, because it can be checked locally in matter of seconds.
This messages tells you to run `yarn run prettier`, which will fix issues automatically.

**Comment by sweever** [comment]
@Sekhmet thank you :100:

**Comment by Sekhmet** [comment]
We prefer to bind instead of using arrow functions. Can you [apply](https://stackoverflow.com/questions/2249852/how-can-i-apply-a-patch) this patch?
```diff
diff --git a/src/client/components/Navigation/Topnav.js b/src/client/components/Navigation/Topnav.js
index 16b5d49..e13ee22 100644
--- a/src/client/components/Navigation/Topnav.js
+++ b/src/client/components/Navigation/Topnav.js
@@ -49,6 +49,8 @@ class Topnav extends React.Component {
       searchBarValue: '',
     };
 
+    this.handleMoreMenuSelect = this.handleMoreMenuSelect.bind(this);
+    this.handleMoreMenuVisibleChange = this.handleMoreMenuVisibleChange.bind(this);
     this.handleSelectOnAutoCompleteDropdown = this.handleSelectOnAutoCompleteDropdown.bind(this);
     this.handleAutoCompleteSearch = this.handleAutoCompleteSearch.bind(this);
     this.handleSearchForInput = this.handleSearchForInput.bind(this);
@@ -56,13 +58,15 @@ class Topnav extends React.Component {
     this.hideAutoCompleteDropdown = this.hideAutoCompleteDropdown.bind(this);
   }
 
-  onSelect = key => {
+  handleMoreMenuSelect(key) {
     this.setState({ popoverVisible: false }, () => {
       this.props.onMenuItemClick(key);
     });
-  };
+  }
 
-  onVisibleChange = visible => this.setState({ popoverVisible: visible });
+  handleMoreMenuVisibleChange(visible) {
+    this.setState({ popoverVisible: visible });
+  }
 
   menuForLoggedOut = () => {
     const { location } = this.props;
@@ -126,10 +130,10 @@ class Topnav extends React.Component {
               placement="bottom"
               trigger="click"
               visible={popoverVisible}
-              onVisibleChange={this.onVisibleChange}
+              onVisibleChange={this.handleMoreMenuVisibleChange}
               overlayStyle={{ position: 'fixed' }}
               content={
-                <PopoverMenu onSelect={this.onSelect}>
+                <PopoverMenu onSelect={this.handleMoreMenuSelect}>
                   <PopoverMenuItem key="my-profile" fullScreenHidden>
                     <FormattedMessage id="my_profile" defaultMessage="My profile" />
                   </PopoverMenuItem>
```

**Pull request merged**
