### PR TITLE
Fix text in activity page for overflow in table rows for non parsed user activity actions

### LINKED ISSUE #1128: Text in activity page overflows the table rows
Copied from Utopian.

<div><h1>The issue of table display</h1>
<p>Using Firefox to visit Busy.org and show 'Activity' of myself (@rmb), some cells in the first column of the comment_options out of the range, and overlapped with the text in the second column. See the Screenshot of Firefox and pay attention to the areas in red boxes:<br>
</p>
<p>On the other hand, if we use Safari, this bug does not appear:<br>
</p>
<h1>How to reproduce this issue</h1>
<ol>
<li>Use Utopian.io to submit a new post. The reason is that the post of Utopian.io has comment options. Alternatively, you can also find a user who recently posted a contribution with Utopian.io.</li>
<li>Use Firefox to visit the Busy.org homepage of the user who just posted a contribution with Utopian.io. For my case the link is: <a href="https://busy.org/@rmb" target="_blank" rel="nofollow noopener">https://busy.org/@rmb</a></li>
<li>Click 'Activity'. For my case, you can go to this link directly: <a href="https://busy.org/@rmb/activity" target="_blank" rel="nofollow noopener">https://busy.org/@rmb/activity</a></li>
<li>Find the 'comment_options' entry in the browser</li>
</ol>
<h1>Environments</h1>
<ul>
<li>macOS Sierra</li>
<li>Firefox 57.0</li>
</ul>
<p><br></p><hr><em>Posted on <a href="https://utopian.io/utopian-io/@rmb/bug-hunting-busy-org-table-display-out-of-range-with-firefox" target="_blank" rel="nofollow noopener">Utopian.io -  Rewarding Open Source Contributors</a></em><hr><p></p></div>

### PR DESCRIPTION
**Pull request by jm90m**
Fixes #1128 .

Changes:
- add div tag surrounded label and add `overflow-x: auto` css style properties to child to fix issue with firefox
- https://stackoverflow.com/questions/16328233/overflow-auto-does-not-work-in-firefox

### CODE REVIEW

**Comment by jm90m** [comment]
@Sekhmet @bonustrack need review whenever you guys got time, no rush, this is for firefox, idk how many users use firefox but this fix should work across all browsers now~

**Comment by bonustrack** [comment]
I think it looks better if the scroll use all the available width like this:
image

**Comment by jm90m** [comment]
@bonustrack not too sure what you mean about your comment about the scroll using entire width?

**Comment by bonustrack** [comment]
I would prefer that the scroll start and end in the green lines rather than in the red lines
image

**Comment by jm90m** [comment]
I see, so add padding to the scrolls? this just for the label or also for the values? i don't think it makes sense for the values

**Comment by jm90m** [comment]
@bonustrack just updated, please re-check when you have time! thx!

**Pull request merged**
