### PR TITLE
Editor: Place Cursor & Newline After Inserted Image

### LINKED ISSUE #811: Image upload sends cursor to the end of the draft and adds a blank line
editor-cursor

#### Expected behavior

Cursor should stay right after the uploaded image.

#### Actual behavior

The cursor jumps to the end of the draft and a blank line is added.

#### How to reproduce

1. Write some text in the editor.
2. Upload image before the text. (not at the end)
3. The cursor jumps to the end and a blank line is added.

* Browser: Chrome 61.0.3163.100
* Operating system: Windows 10

### PR DESCRIPTION
**Pull request by ryanbaer**
Fixes #811 

This fix ensures that, when inserting an image:
- the newline placed after the image is no longer placed at the end of the input
- the cursor is no longer placed at the end of the input

Putting the newline into the correct position was an easy fix.

Ensuring the cursor gets placed directly after the inserted image (as opposed to at the end of the input) took a little more work.

### CODE REVIEW

**Comment by jm90m** [comment]
can we deploy this to `busy-dev-pr` so we can test it out?

**Comment by bonustrack** [comment]
Yes on the way @jm90m

**Comment by jm90m** [comment]
Everything is working on my end, code looks fine, maybe @Sekhmet might have some comments?

**Comment by ryanbaer** [comment]
Thanks for the review @jm90m

**Comment by ryanbaer** [comment]
Thanks for the review @Sekhmet.

Whoever has appropriate permissions, this is ready for merge.

**Pull request merged**
