### PR TITLE
Add back to the top button

### PR DESCRIPTION
**Pull request by th7nder**
Fixes Issue: #1407 

Adds back to the top button.
### Summary of Changes
* added BackTop component from antd
### Screenshots/Videos
gifffff

### CODE REVIEW

**Comment by bonustrack** [comment]
@pareshUD do you have a better icon or suggestion for the design?

**Comment by pareshUD** [comment]
two column editor

Please check this and let me know if any changes are there

**Comment by pareshUD** [comment]
go to top

**Comment by bonustrack** [comment]
We may need to change the behavior on mobile so the button don't appear all the time on top of the feed. Maybe on small screen show the icon only if the screen no move for 5sec. What do you think @pareshUD. Otherwise the icon is good, can you add it on iconfont @pareshUD ?

**Comment by pareshUD** [comment]
@bonustrack Uploaded the back to top arrow to iconfont.cn

**Comment by bonustrack** [comment]
@th7nder Can you update the iconfont url to `//at.alicdn.com/t/font_317125_wqz6u4c8idi8jjor.css` and use `icon-back-top` for the back to top icon?

**Comment by th7nder** [comment]
Ok, will do. Thanks!

**Comment by th7nder** [comment]
Ok! I think I've done the changes, icon is updated and button toggles.
Button shows up when you scroll down a bit, and then you start to scroll up.
It hides when you start scrolling down again.

**Pull request merged**
