### PR TITLE
Add 2 Column Editor

### LINKED ISSUE #1334: Full width 2 colums editor

### PR DESCRIPTION
**Pull request by jm90m**
Fixes #1334 

- WIP Still ~ do not review

### CODE REVIEW

**Comment by bonustrack** [comment]
My review
- Can you use pointer cursor on mouse over expand button and move it to right side?
- On mobile we should remove the right column (preview) on the expanded editor

@pareshUD Can you make a new proposal design based on the review we made in Discord #voice?

**Comment by pareshUD** [comment]
two column editor

Please check this

**Comment by jm90m** [comment]
@pareshUD Minimize and close are the same thing?

**Comment by jm90m** [comment]
@pareshUD that doesn't make sense, when you close the editor, where do you go? Don't you go back to the smaller editor view?

**Comment by bonustrack** [comment]
@pareshUD 
1: Can you use our current logo and current icons set? Also remove the options we dont currently have on editor like video or poll
2: Keep only minimize link and remove "Close"
3: Buttons should be "Delete this draft" and "Post", similar than current small editor
4: Can you move the word count and min read on top right?
5: How does it look when your scroll?

image

@jm90m can we have it on a separated page like `/full-editor`?

**Comment by pareshUD** [comment]
@bonustrack Thanks for the feedback. Let me update you this changes and send you

**Comment by bonustrack** [comment]
Dont forget to add design file @pareshUD

**Comment by pareshUD** [comment]
2 column editor

**Comment by jm90m** [comment]
is this the final design?

**Comment by bonustrack** [comment]
Yes @jm90m this design is good. We just need to change "Post" and "Delete draft" buttons and use same button style than on normal editor.

**Comment by jm90m** [comment]
@Sekhmet I'm going to close this, so I can focus on mobile app @bonustrack

**Comment by bonustrack** [comment]
We can keep the PR open so we dont miss it.

**Comment by Sekhmet** [comment]
Moved to #1855.

**Pull request closed without merging**
