### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by nil1511**

### CODE REVIEW

**Comment by adcpm** [comment]
I have one test failing with this error:
image

**Comment by nil1511** [comment]
@adcpm Please check whether your dependencies are updated.

**Comment by adcpm** [comment]
Seem to work now, i had to do `npm test -- -u` to update snapshots.

**Comment by bonustrack** [comment]
[CircleCi setup storybook test](https://trello.com/c/nWimtTyc/34-circleci-setup-storybook-test)

**Pull request merged**
