### PR TITLE
Add Loading to Est Account & Steem Trending Charts

### LINKED ISSUE #929: SP amount in "Claim Rewards" transactions is not SP
#### Expected behavior

The number in Claim Rewards transactions should be actually SP.

image

#### Actual behavior

The number is much higher. It seems that it is VESTS (not confirmed).

image

#### How to reproduce

1. Go to wallet
2. Find "Claim Rewards" transaction
3. Compare with Steemit

* Browser: Chrome
* Operating system: Windows 10

### PR DESCRIPTION
**Pull request by jm90m**
Fixes #929.
* Est. account value doesn't show up

Changes:
- Add loading to Est Account Value
- Add loading to steem trending charts

### CODE REVIEW

**Comment by bonustrack** [comment]
Sometime there is a `NaN` showed while loading. Also for the Estimated account value i don't see loading icon but `0.00$` i think the loading icon is less confusing.
image

**Comment by bonustrack** [comment]
On small screen (when sidebar are not visible) we should remove border on left & right and border-radius of the boxes in center (similar than on the feed):
image

**Comment by bonustrack** [comment]
Just spoted this also, something wrong with SP conversion for claim reward, i did not claim 54K SP :)
image

**Comment by jm90m** [comment]
@bonustrack just made those fixes you requested

**Comment by bonustrack** [comment]
@jm90m border radius should be removed too on small screen:
image

**Comment by jm90m** [comment]
@bonustrack done, removed border radius for small screens

**Comment by bonustrack** [comment]
You need to remove all of them.
image

**Comment by bonustrack** [comment]
Also remove double border here:
image

**Comment by jm90m** [comment]
@bonustrack good catch just removed

**Pull request merged**
