### PR TITLE
Use getStateAsync instead of getAccountHistoryAsync for User Wallet Transactions

### PR DESCRIPTION
**Pull request by jm90m**
So I've been thinking about this, right now we getAccountHistoryAsync, but when we use that, we have to filter through every single user action just to get the wallet transactions. So even though we get 2500, sometimes it won't be all of the user's wallet transactions... so how would we know when the user has more wallet transactions?

Also for this, I tried to use React Infinite: (https://github.com/seatgeek/react-infinite) 
* but it has issues when rendering element sizes of dynamic heights (https://github.com/seatgeek/react-infinite/issues/231)

After trying to get React Infinite to work, I settled on using what we currently have, `ReduxInfiniteScroll`.

Let me know your thoughts @Sekhmet @bonustrack  

Fixes # 
https://github.com/busyorg/busy/issues/928

Changes:
- Use getStateAsync instead of getAccountHistoryAsync to get user transaction history

### CODE REVIEW

**Comment by bonustrack** [comment]
@jm90m It was intentional to use getAccountHistory instead of getState. getState dont scale, there is no pagination and can give a too much big file to download for users. That's not conveninant at all for mobile. Also with getAccountHistory we have all data, which make it possible to create page "Activity" in same time and get data for notifications later.

**Comment by Sekhmet** [comment]
We already got `react-infinite-scroller`. Would it work?

**Comment by jm90m** [comment]
@bonustrack The problem I faced with `getAccountHistory` is that there is no way to tell when a user has anymore wallet transactions. So for example on the first request to `getAccountHistory`, I get the first 2500 records, but say only 4 of them are wallet transactions. That doesn't fill the page all the way down to the infinite scroll portion. So how would we know when to fetch more records?

**Comment by jm90m** [comment]
@Sekhmet yeah I think `react-infinite-scroller` will work but is that better than the `redux-infinite-scroll` ? I see the ReduxInfiniteScroll is used in 2 other places (Feed / UserList)

**Comment by bonustrack** [comment]
@jm90m We should use `getAccountHistory` it doesnt matter if some requests dont give results, if there is more than `x` empty result requests you can stop the loop.

**Comment by jm90m** [comment]
@bonustrack alright thats fine with me, I'll keep looking into making it work with getAccountHistory, closing this and moving to new branch.

**Pull request closed without merging**
