### PR TITLE
Add Notifications

### PR DESCRIPTION
**Pull request by Sekhmet**
**Notifications** component:
image

### CODE REVIEW

**Comment by adcpm** [comment]
I've added more data for notification but I've not been able to test the scrollbar. Can you make take we can see max 5 stories and if there is more, scrollbar appear on mouse over notification popover.

**Comment by Sekhmet** [comment]
peek 2017-06-07 14-04

**Comment by adcpm** [comment]
Can we have also the tooltip "Notification" on mouse over.
image
And for the top right button of logged header we can have a popover with this in menu:
- Activity
- Settings
- Logout

**Comment by Sekhmet** [comment]
peek 2017-06-07 14-40

**Pull request merged**
