### PR TITLE
Update collecting data from form

### LINKED ISSUE #1412: Post content inside reward selector bug
See here https://busy.org/utopian-io/@deadzy/bug-draft-reward-busy-2-3-0

### PR DESCRIPTION
**Pull request by Sekhmet**
Fixes #1412

Changes:
- Collect data from form using `getFormValues`.

### CODE REVIEW

**Comment by Sekhmet** [comment]
Can I get review on this? I'm working on #1450 and it would be great to have those changes merged.

cc @bonustrack  @jm90m

**Comment by bonustrack** [comment]
This doesnt work for me
image

**Comment by Sekhmet** [comment]
This doesn't change already saved data. Only prevents saving new posts with this bug.

**Comment by Sekhmet** [comment]
I can add check that will test if reward option is correct on load in this PR though.

**Comment by jm90m** [comment]
screen shot 2018-02-01 at 7 59 33 pm

I tried to create a new post, looks like rewards is still bugged?

**Comment by Sekhmet** [comment]
You created new post using this PR deployment?

**Comment by jm90m** [comment]
yeah I used the latest deployment a few hrs ago. other ones on hellosteem are not from this PR. I dont think the actual create went through for me. Will try again now

**Comment by Sekhmet** [comment]
I added code that checks if reward is valid and resets it if needed (we might delete it after a month or so).
Can I get quick review of changes?

cc @jm90m @bonustrack

**Pull request merged**
