### PR TITLE
Update tooltip color

### LINKED ISSUE #1451: Change tooltip color
- Change tooltip color to `#282828`
image

### PR DESCRIPTION
**Pull request by jm90m**
Fixes #1451

Changes:
- Use tooltip color outlined in #1451

### CODE REVIEW

**Comment by bonustrack** [comment]
You are missing the arrow in bottom of tooltip. It still purple now.

**Comment by jm90m** [comment]
@bonustrack woops just fixed

**Comment by Sekhmet** [comment]
https://github.com/busyorg/busy/blob/2c94427afe08da48c0b461c948a1e12af75d43da/src/client/styles/custom.less#L53-L55

I think we can use those to change colours.

**Comment by jm90m** [comment]
@Sekhmet good idea, just updated

**Pull request merged**
