### PR TITLE
add powerdown tooltip kr translation

### PR DESCRIPTION
**Pull request by economicstudio**
Related to #2147, #2162

### Changes

* Add kr translation

### Test plan

* [ ] Set language as kr
* [ ] Check tooltip on powering down amount: http://localhost:3000/@steemit/transfers

### CODE REVIEW

**Comment by Sekhmet** [comment]
We add translations through Crowdin (https://crowdin.com/project/busy).
Can you add this translation to Crowdin? We would import new translations and release a new version soon.
Thanks.

**Comment by economicstudio** [comment]
@Sekhmet Thanks. I've made an account, but it seems that I have no authorization to add or change something. My crowdin id is blockchainstudio (same as steemit id). Could you give me the permission? I'm native in Korean and I translated bitcoin whitepaper, which is in the bitcoin whitepaper github.

**Comment by Sekhmet** [comment]
I've made you a proofreader so you should be able to add translations and confirm them. Before you were a translator (default role) which should make it possible to add translations though.
Can you verify that now it works?

**Comment by economicstudio** [comment]
Thanks I can see that now I'm a proofreader, but it seems I can't still add translation. Since I'm new to crowdin, I may miss something. How to add translation? I can't find how intuitively. There is no button to add, and I tried to upload a new file, but it didn't work. Thanks.

**Comment by Sekhmet** [comment]
You go there, search for text you want to add and suggest new translation:
https://crowdin.com/translate/busy/31/en-ko

**Comment by economicstudio** [comment]
I know that page, but what I'm saying is, I can edit, but I can't add a new string, e.,g, "steem_power_pending_withdrawal_tooltip"

**Comment by Sekhmet** [comment]
You can't add new translations from CrowdIn. We will have to sync it from GitHub and then you can translate all translations from default.json

**Comment by economicstudio** [comment]
Thanks, I'll wait then.

**Pull request closed without merging**
