### PR TITLE
Adds Witnesses Page

### PR DESCRIPTION
**Pull request by Kennybll**
Adds Witness Page.

Changes:
- Adds Witnesses Page in Routes
- Adds new functions to apiHelpers and sortHelpers
- Adds witnessesReducer to reducers

### CODE REVIEW

**Comment by bonustrack** [comment]
@Kennybll You should ask a core member of Busy before working on feature, specially when we don't explicitly ask for this feature, there should be an issue or card in GitHub Project for it if it's something we approved. Your design proposal is very different from what we have on others pages on the sites. We can't approve your PR like that, we need a mockup for this otherwise you will spend lot of time in this PR.

**Comment by Kennybll** [comment]
It is under the Github workflow, as Add an option to vote for a witness. What do you mean by mockup?

**Comment by bonustrack** [comment]
I mean we should agree on a design with @pareshUD before doing the integration to avoid too much changes.

**Comment by Kennybll** [comment]
So should I close this pull request, or should I contact pareshUD?

**Comment by Sekhmet** [comment]
You shouldn't start writing code if that feature hasn't been discussed yet. First create an issue, let others give their opinions on the topic, make sure we have everything figured out (features, look and feel, the way it should be implemented) and then announce that you are willing to work on it, this way:
1. We don't waste time implementing things that will have to be changed (in some cases rewritten from ground up).
2. No two developers would work on the same feature making one's developer work useless.

You can take a look at those guidelines, they are not accepted yet, but I think it's good starting point and noone would get hurt by respecting those:
https://github.com/busyorg/busy/issues/903

**Comment by jm90m** [comment]
Thanks for the contribution for this PR, but I'll be closing this PR since @Sekhmet or @bonustrack  has not approved of this. We can always reference this PR back when it is time to create a `Witness Page` with designs from @pareshUD.

**Pull request closed without merging**
