### PR TITLE
Comment form should not be cleared on upvote #807

### PR DESCRIPTION
**Pull request by SimpliciTea**
in components/Comments/CommentForm.js:

-- move this.setState({ inputValue: '' }) from
   componentWillReceiveProps to onSubmit method

I believe that this creates the intended behavior, although I'm not positive
that I see everything that the prior componentWillRecieveProps was doing

### CODE REVIEW

**Comment by bonustrack** [comment]
Thank you for your PR @SimpliciTea. I spotted an issue when i click "Comment" to send a comment, the textarea will be cleared. It should not be the case:
comment

**Comment by SimpliciTea** [comment]
@bonustrack So it should not clear on upvote or comment submission. It should clear on comment submission success?

**Comment by Sekhmet** [comment]
I can't figure out what @bonustrack means exactly from this GIF, but we should clear comment form after submission success, but only the comment form which was submitted. If there were other comment forms opened and some text was typed into them they should remain in the same state even after submitting one of them, so only one of them is cleared after submitting (the one that succeeded).

**Comment by bonustrack** [comment]
What i mean in the GIF is that my comment is hidden in the input when i hit the button "Comment". Instead of my comment, I see the placeholder "Write a comment". On current busy version it's not the case. It's confusing and if comment fail to be sent i think it's lost.

**Comment by bonustrack** [comment]
@SimpliciTea Yes it should be cleared only on comment success only.

**Comment by ryanbaer** [comment]
I don't think the package-lock.json file should be committed unless the scope of your PR actually required it - i.e. adding / updating / removing a dependency or something. It doesn't seem to me that the file should've been committed here, right?

**Comment by bonustrack** [comment]
Agree with @ryanbaer about the file `package-lock.json`, as there is no change in `package.json` i think it should not be commited on this PR @SimpliciTea.

**Comment by bonustrack** [comment]
I'm closing with PR due to inactivity

**Pull request closed without merging**
