### PR TITLE
padding fixes

### PR DESCRIPTION
**Pull request by mktcode**
On medium screens there was no padding around the content.

border-medium-screens

border-medium-screens2

I hope this time there's not much to debate... @bonustrack :P

### CODE REVIEW

**Comment by bonustrack** [comment]
Thank you that's great. Can you just make the end of search input aligned to the feed?
image

**Comment by mktcode** [comment]
done

**Comment by mktcode** [comment]
Well... I don't feel very comfortable doing a report for every few lines of code I changed... :/
But there will be a report from me today about something else... I'll post it as soon as @heimindanger posted his update on dtube. ;)

**Comment by bonustrack** [comment]
Works for me :)

**Pull request merged**
