### PR TITLE
Use HighCharts for Market Sidebar

### LINKED ISSUE #1220: Update Market Sidebar to use HighCharts with new Design
Update Market Sidebar to use HighCharts with new Design

Design:

market_sidear_expanded

### PR DESCRIPTION
**Pull request by jm90m**
Fixes #1220.

Changes:
- use react-highcharts
- display charts with locale in x-axis

screen shot 2017-12-20 at 9 18 12 am
screen shot 2017-12-20 at 9 18 34 am

### CODE REVIEW

**Comment by bonustrack** [comment]
Looking good. Is it possible to make the chart line starting in the red line?
image

**Comment by jm90m** [comment]
@bonustrack yeah will try to update styles

**Comment by jm90m** [comment]
@bonustrack just updated it to be more aligned, how about something like this?

screen shot 2017-12-20 at 11 45 31 am

**Comment by bonustrack** [comment]
Then, can you try to make it start and end on red line?
image

**Comment by jm90m** [comment]
wait @bonustrack I just pushed to change to align the line to how you wanted it before see here

screen shot 2017-12-20 at 12 32 22 pm

**Pull request merged**
