### PR TITLE
fixed button positioning on invite page

### LINKED ISSUE #1443: Invite button may overflow the link box
#### Expected behavior

The button "Copy link" should remain within the link box and be pull to the right border of the box.

image

#### Actual behavior

The button overflows the link box with different button text. If the text is short, there is a blank space on the right of the button.

image

image

#### How to reproduce

A)
1. https://staging.busy.org/invite
2. click the copy link button

B)
1. change the button text to be longer
2. https://staging.busy.org/invite

* Browser: Chrome 63.0.3239.132
* Operating system: Windows 10

### PR DESCRIPTION
**Pull request by mightypanda-x**
Fixes #1443

### Changes
Updated copy button to move to right of the invite box.
Summary of changes you made.

* Updated button to relative positioning.
* Updated container to flex box.
* Changed size of button to match the input box

### Test plan

Open invite page.
Button should be on the right of the invite input box.
Click on the button. This should change the text to copied.
Button should still be on the right of the button.

### Demo (optional)

Sreenshots (before & after) or video that show result of your work.

image

image

### CODE REVIEW

**Comment by mightypanda-x** [comment]
Hi @jm90m 
That's what @bonustrack discussed in this PR : https://github.com/busyorg/busy/pull/1925

**Comment by jm90m** [comment]
@mightypanda-x oh good catch, sorry I missed that!

**Comment by Sekhmet** [comment]
Would it be possible to prevent button text from wrapping on smaller screens?

image

**Comment by mightypanda-x** [comment]
Fixed

**Comment by Sekhmet** [comment]
Thanks a lot!

**Pull request merged**
