### PR TITLE
Remove black gaps on mobile layout (User Cover Image)

### PR DESCRIPTION
**Pull request by hernandev**
This is a simple fix on the black cover image gaps on mobile layout.

From:

To:

### CODE REVIEW

**Comment by jm90m** [comment]
Does this work for you @bonustrack ?

I don't see it working on here: https://busy-master-pr-1640.herokuapp.com/@hernandev

screen shot 2018-03-13 at 4 07 27 pm

**Comment by hernandev** [comment]
@jm90m sorry, I haven't actually ran this, just locally edited then applied on the less file directly on Github, just made another commit since there was a parent rule on the cover size.

Is the link automatically updated?

**Comment by bonustrack** [comment]
The cover image has black border in top and bottom see source: http://www.timosart.com/GameArt/GoW_A_DelphiSky02.jpg, i dont think there is an issue on how Busy render it.

**Comment by hernandev** [comment]
@bonustrack can't believe it. the CSS I was setting was just cutting the black borders off.

I'll take a moment to realize how insane this was.

Sorry for the lost time guys!

P.S. setting as auto, would prevent the issue on non standard sizes, I guess, but just feel free to close this.

Thank you and sorry!

**Comment by bonustrack** [comment]
This was tricky, no pb @hernandev. I'm closing this PR i think `cover` is more flexible :)

**Comment by hernandev** [comment]
Cool. thanks!

**Pull request closed without merging**
