### PR TITLE
Make Comments header responsive

### LINKED ISSUE #822: Comments sorting options don't fit the line in some languages
Czech language

English for comparison

#### Expected behavior

Comments sorting options don't overflow.

#### Actual behavior

With some languages, the sort options may overflow because the words are too long.

#### Steps to reproduce

1. Set Czech language. (It may occur with others too.)
1. Open a post on a mobile.
1. See comments.

- Browser: Brave
- Operating system: Android 7.1.2

### PR DESCRIPTION
**Pull request by Sekhmet**
Fixes #822 

image

Changes:
- Add `SortSelector` component.
- Use `SortSelector` for feed and comments sorting.

### CODE REVIEW

**Comment by bonustrack** [comment]
I think a dropdown would fit better in mobile

**Comment by Sekhmet** [comment]
I'm not big fan of dropdowns where normal links would work just well. What do you think @pareshUD?

**Comment by jm90m** [comment]
Icons would be better if people can differentiate, which one is which, imo, but I'll let @pareshUD handle design :)

**Comment by bonustrack** [comment]
Dropdown fill into same line than `Comments` title, it's more ergonomic to use same line than creating a new line.

**Comment by bonustrack** [comment]
Icon is confusing, user has to learn what is what..

**Comment by Sekhmet** [comment]
I updated it to use selector:
image

However, I will mark it as "Needs update", because for some reason it's causing feed to render posts with the same keys.

**Comment by Sekhmet** [comment]
It looks like it's not this PR that causes duplicate keys, so I will remove "Needs update" badge and leave it for review.
I will work on duplicate keys here: #1469

**Pull request merged**
