### PR TITLE
Add Trending Tags Slider to mobile home feeds

### PR DESCRIPTION
**Pull request by jm90m**
Changes:
- Add trending tags to mobile home feeds for unlogged/logged users

screen shot 2018-03-21 at 6 27 35 pm

### CODE REVIEW

**Comment by jm90m** [comment]
image

This is what it looks like on my iphone 7+

**Comment by bonustrack** [comment]
I'm not 100% convincing about the UX. @pareshUD can you explore some alternative design for solving this problem (being able to browse tag on mobile view)

**Comment by pareshUD** [comment]
add topic list
add topic
topic selected

@bonustrack @Sekhmet Please check this and let me know

**Comment by jm90m** [comment]
@pareshUD I don't understand, are the trending tags a modal popup now?

**Comment by bonustrack** [comment]
@pareshUD can you try a different design with these details:
- Page should take full screen or at least be 70% of the screen (similar than like list modal)
- Show one topic per line so it's more readable, expect there is 30 tags and scroll
- Use only the first word first letter uppercase, the others words should have lowercase
- Change `Select Tag for Topic` to `Trending topics`
- I'm not too fan of the button `+ Add Topic` maybe you can find another way to display that
- We should not add new style for tag, actually the grey colored tag you propose we dont have it on the website and this feature dont need that we change the way we display tags.

**Comment by pareshUD** [comment]
@jm90m Its not a popup like popup but its a slideout.. Like we do for sort by in mobile

**Comment by pareshUD** [comment]
@bonustrack Sure let me work on those changes andn update you

**Comment by pareshUD** [comment]
trending topics

@bonustrack can you check this

**Comment by bonustrack** [comment]
@jm90m can you integrate Paresh design but change Add Topic to 
image
Make topic lowercase and make sure it scroll well on mobile.

**Comment by bonustrack** [comment]
Can you remove the top border on first row here so we dont get double border?
image
Can you use the same popover header style than the notification popover?
image

**Pull request merged**
