### PR TITLE
Subscribe to Notifications & Add Notification Popup

### PR DESCRIPTION
**Pull request by jm90m**
Changes:
 - Still a WIP but creating PR to test and get feedback
 - Had to upgrade to antd 3.0.0 since I was having trouble with notifications component - https://github.com/ant-design/ant-design/issues/8115
 - **Important:** Since I upgraded antd, some components might not function as normal or might be styled weird, I caught a few things that were wrong with the editor due to the upgrade, but there might be more
 - Add NotificationPopup Component
 	- Had to use @withRouter and @injectIntl since `<Link/>` and `<FormattedMessage/>` were not working, 
 	I guess since the notifications popup gets created outside the react dom tree

screen shot 2018-03-16 at 11 25 51 am

### CODE REVIEW

**Comment by bonustrack** [comment]
@jm90m you need to update yarn.lock file

**Comment by jm90m** [comment]
## Also check to see if anything is wrong with antd since antd version upgrade
- [ ] Home Page
   - [ ] unlogged user
   - [ ] logged user
- [ ] PostModal
    - [ ] Reply to post
    - [ ] Reply to comments
- [ ] Category Feed
- [ ] User Profile
     - [ ]  Blog
     - [ ] Comments
    - [ ] Followers / Following
    - [ ] Wallet
    - [ ] Activity
- [ ] Sidebar Widgets
    - [ ] Crypto Charts
   - [ ] Activity Filter
   - [ ] Interesting People
   - [ ] Top Reblogged
- [ ] Logged in user
   - [ ] Activity
   - [ ] Bookmarks
   - [ ] Edit Profile
    - [ ] Invite
   - [ ] Settings
   - [ ] Drafts
   - [ ] Notifications
- [ ] Discover More people

**Comment by bonustrack** [comment]
Can you make the avatar clickable too @jm90m ?

**Comment by jm90m** [comment]
yup @bonustrack

**Comment by bonustrack** [comment]
Easy way to test this is to comment on your own post.

**Pull request merged**
