### PR TITLE
Remove border-left/right and border-radius in Wallet/Activity page

### LINKED ISSUE #1929: Wrong border on small screen for activity and wallet pages
1: On activity and wallet pages there should not be right border on small screen here:
image
2: The top right corner should not have white background

### PR DESCRIPTION
**Pull request by alokpant**
Fixes #1929

### Changes

Summary of changes you made.

Changes only affect Mobile version:
* Remove border left and right for blocks in Wallet/Activity page
* Remove border-radius for Wallet/Activity page

### Test plan

Explain how to test changes you made.

Visit following urls in mobile:

* http://localhost:3000/@husaini/transfers
* http://localhost:3000/@husaini/activity

### Demo (optional)

Before is available in issue.
After versions:

**Wallet**
screen shot 2018-06-02 at 09 31 33

---
**Activity**
screen shot 2018-06-02 at 09 32 02

### CODE REVIEW

**Comment by alokpant** [comment]
Hey guys, is this going to be merged? It has been stale for 9 days now. If there are no plans to merge it then please close it. Thank you.

**Comment by bonustrack** [comment]
@alokpant we will look on it today, (team were off for 1 week)

**Comment by bonustrack** [comment]
Thank you for your contribution @alokpant it looking almost perfect, is it possible to remove this right border when wallet page is loading?
image

**Comment by alokpant** [comment]
@bonustrack Will look into it tonight, and push something.

**Comment by alokpant** [comment]
@bonustrack I tried to figure out when this happens. I tried looking at it for mobile and desktops but it is not visible for me. Can you please provide more context to this? For which screen size does it happen?

**Comment by bonustrack** [comment]
@alokpant On desktop it happen for me when i go into user wallet, and i scroll the page like here: https://busy-master-pr-1935.herokuapp.com/@hellosteem/transfers .

**Comment by alokpant** [comment]
@bonustrack I still can't see it. I am testing on Brave, Firefox. Which browser are you using?

screen shot 2018-06-15 at 06 58 24

screen shot 2018-06-15 at 06 59 17

**Comment by bonustrack** [comment]
@alokpant You need to reduce the width of the window so its show everything in 1 column. Im using Chrome.

**Comment by Sekhmet** [comment]
It happens in 1 column layout (360px for example):
image

You might use Chrome networking throttling to make it easier to debug.

**Comment by alokpant** [comment]
@bonustrack @Sekhmet Fixing it now. Looks like for Tablets viewport.

**Comment by alokpant** [comment]
@bonustrack @Sekhmet Please review. I have removed border and also border-radius for smaller devices.

**Comment by Sekhmet** [comment]
Looks good to me.
cc @bonustrack

**Comment by bonustrack** [comment]
Here there should be borders should have border-radius when its not on small screen
image

**Comment by alokpant** [comment]
@bonustrack there should be. Will look into it during weekend and push a fix.

**Comment by alokpant** [comment]
@Sekhmet @bonustrack Sorry guys. Couldn't do it last week. I was busy pushing a project live. I pulled from latest master. I am getting error:
```
Error: Cannot find module "remarkable"
    at webpackMissingModule (webpack:///./src/client/components/Story/Body.js?:44:83)
```
I just pulled from latest master.

**Comment by alokpant** [comment]
Nevermind, forgot to do yarn. Beginners mistake.

**Comment by alokpant** [comment]
screen shot 2018-06-30 at 09 29 57
screen shot 2018-06-30 at 09 30 04

@bonustrack I have added border for medium and bigger screens please review.

**Comment by alokpant** [comment]
@Sekhmet First image is from Wallet and Second image is from Activity page. It seems consistent. I will test it again tonight and see if I missed something.

**Comment by Sekhmet** [comment]
It looks okay if everything is loaded, but border is different when Loading icon is displayed.

**Comment by Sekhmet** [comment]
We changed default branch to `develop`. Can you update it whenever you are ready?

**Comment by Sekhmet** [comment]
Seems to be working very well. Thank you!

**Pull request merged**
