### PR TITLE
Add Follows you to users that follow you when viewing their profile page

### LINKED ISSUE #964: [Feature Proposal] "Follows You" indicator
Per our new development guidelines, I wanted to have discussion / get approval to begin working on a feature I proposed on Utopian.

You can read the full post here: [Utopian: Busy Feature Idea: "Follows You" indicator](https://utopian.io/utopian-io/@ryanbaer/busy-feature-idea-follows-you-indicator)

But here are some screenshots which convey what I had in mind:
image

image

### PR DESCRIPTION
**Pull request by jm90m**
Add "Follows you" to users that follow you when viewing their profile page

Fixes #964

Changes:
- Add getAllFollowers for  current authenticated user
- display "Follows you" if you use follows you

### CODE REVIEW

**Comment by bonustrack** [comment]
It take a while (around 6 seconds) till `Follow you` appear if i open a profile with a fresh tab, are you loading all the list of followers? 
test

**Comment by bonustrack** [comment]
There should be only 1 request to check if user A follow user B.

**Comment by jm90m** [comment]
@bonustrack what request is that?

**Comment by jm90m** [comment]
idk whats going on with this PR but, I'm going to create a new PR that makes the request more optimized, i had lots of merge conflicts and im on a laptop and not at my home setup, so im gonna close this PR and reference it later. and work on it when im done on my trip, i cant get a few things to work for some reason, idk if its cuz im still sick or tired/or whatever but yeah, this feature doesnt seem to important, so ill close this PR and make new one when I get back to Boston

**Pull request closed without merging**
