### PR TITLE
Fix for drafts not saving correctly

### LINKED ISSUE #1705: Drafts are stored multiple times
There is an issue atm when writing a post, draft is stored multiple time
image
This issue is on staging.busy.org and busy.org

### PR DESCRIPTION
**Pull request by jm90m**
Fixes #1705

Changes
- url was not updated for new drafts

### CODE REVIEW

**Comment by bonustrack** [comment]
This is still not working for me. The same post is being saved multiple time.
image

**Comment by Sekhmet** [comment]
Redirecting to draft is already handled, but there was a typo that was preventing it from happening:
```diff
diff --git a/src/client/post/Write/Write.js b/src/client/post/Write/Write.js
index ce1d1c7..82e315a 100644
--- a/src/client/post/Write/Write.js
+++ b/src/client/post/Write/Write.js
@@ -234,7 +234,7 @@ class Write extends React.Component {
 
     if (isBodyEmpty) return;
 
-    this.props.saveDraft({ postData: data, id: id || uuidv4() }, !!id);
+    this.props.saveDraft({ postData: data, id: id || uuidv4() }, !id);
   }, 2000);
 
   render() {
```

**Comment by jm90m** [comment]
@bonustrack yeah I can reproduce it, trying to fix it now~

**Comment by bonustrack** [comment]
I'm able to lose some draft, if i edit post A, and while post getting saved i click on draft post B and do a change. This make post B data change to post A.

**Pull request merged**
