### PR TITLE
Add ctrl/cmd + click check for when notifications linked is clicked

### PR DESCRIPTION
**Pull request by jm90m**
Add ctrl/cmd + click check for when notifications linked is clicked

### CODE REVIEW

**Comment by bonustrack** [comment]
There isn't a more natural way to do that? Links should be openable by default without having to code keylogger.

**Comment by jm90m** [comment]
they are openable on default ? Its just @espoem wanted it so notifications popover doesnt get closed when opened with new tab click

**Comment by bonustrack** [comment]
Links are supposed to be openable with ctrl click by default. It's the case on every website, it's just the default behavior. Why do we need to handle it with JS?

**Comment by jm90m** [comment]
So we can see if its a `cmd` or `ctrl` click so notifications popover doesn't close when they do click on it.

**Pull request merged**
