### PR TITLE
Update InterestingPeopleWithAPI component to grab username by props.m…

### LINKED ISSUE #978: Sidebar in discussion changes behaviour if you come from wallet tab
The sidebar in discussion tab in your profile probably shows users with high influence. It shows only people I already follow. This behaviour changes if you go to the wallet tab and back to discussion. After the change I see only people that I do not follow.

## Expected behaviour

The behaviour of the sidebar in the discussion tab should not change.

## Steps to reproduce

1. Go to your profile
2. Click the wallet tab
3. Click the discussion tab

<hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@espoem/sidebar-in-discussion-changes-behaviour-if-you-come-from-wallet-tab">Utopian.io</a></em><hr/>

### LINKED ISSUE #984: Sidebar not working correctly for comments, followed and following
You can see a sidebar in your profile if you click the discussion or wallet tab. For the other tabs, it depends from which tab you come. I use Google Chrome on Windows 10.

## Expected behaviour

Sidebar should be visible/invisible regardless the page or tab we come from.

## Steps to reproduce

1. Go to your profile
2. Follow the steps shown in the gif

<hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@espoem/sidebar-not-working-correctly-for-comments-followed-and-following">Utopian.io</a></em><hr/>

### PR DESCRIPTION
**Pull request by jm90m**
Fixes #984
Fixes #978

Changes:
- Update InterestingPeopleWithAPI component to grab username by `props.match.params` rather than `window.location`

### CODE REVIEW

**Comment by bonustrack** [comment]
The interesting people block is showing the most reblogged user when i load then it switch to a different list not relevant:
wrong-pp
The proper list on profile @fabien should start with @busy.org account as recommended

**Comment by fabien** [comment]
@bonustrack I'm not the @fabien you meant ...

**Comment by jm90m** [comment]
Just added `isFetchingFollowingList` to `InterestingPeopleWithAPI` component since now that `InterestingPeopleWithAP`I component relies on following list, we need to check if it's fetching it

**Comment by bonustrack** [comment]
@jm90m Now on my profile i see only the wrong list, starting with `@team.alpha`, but it should be started by `@busy.org`

**Comment by jm90m** [comment]
no we went over this in https://github.com/busyorg/busy/issues/921, the sidebar filters out people you have already followed.

**Comment by bonustrack** [comment]
Ho right i get it now @jm90m that make sense. It just might feel strange to see on my profile the  rebloged users that i'm not following. Maybe this component should show the already followed users too and not act as the others InterestingPeople in root feed, the title of the block could be "Recommended People". What do you think @jm90m @Sekhmet ?

**Comment by jm90m** [comment]
The InterestingPeople block on the root feed was also changed to filter out people that have already been followed. For me, it doesn't really make sense to show people that you have already followed on the sidebar since you're already following that user, so you wouldn't be interested in seeing him there, you can always just go to your `Following` page. But your call, I'm fine either way :)

**Comment by bonustrack** [comment]
I know that in the root feed it filter out the one you follow already which is good. But when you look into the profile, the block is more like showing for each user "The most reblogged users of the current user profile". It make sense to filter out already followed in root feed but i wonder in profile if that make sense to show "The most reblogged users without the ones i following already".

**Comment by jm90m** [comment]
Maybe we could change the title to "Most Reblogged Users" or something else

**Comment by bonustrack** [comment]
Yes, this title would be self explanatory

**Comment by jm90m** [comment]
@bonustrack just changed the name to `Top Reblogged Users`... do you think we should keep same Icon? I think `Top Reblogged Users` sounds more correct rather than `Most Reblogged Users`. I didn't rename the component since it uses same styles and classNames as InterestingPeople but I can rename it.

**Pull request merged**
