### PR TITLE
Refactor Editor and CommentForms

### LINKED ISSUE #913: [Proposal] Consolidate Editor Components
The codebase currently contains 3 separate, but very similar, Editor components:
- `components/Editor/Editor.js`
- `components/Comments/EmbeddedCommentForm.js`
- `components/Comments/CommentForm.js`

All three of these components are rather long, in particular the Editor itself.

I think we should discuss a way of extracting common functionality. For example, the `insertImage` function between the three files is very similar, and is identical between CommentForm and EmbeddedCommentForm.

Two approaches that spring to mind:
1. Extract common functions like `insertImage` to helper methods, converting any values assumed to be on `this` into additional parameters.
or
2. Create a base class component (`BaseEditor`, but maybe with a better name), which contains the core functionality of an editor, and then all 3 implemented editors extend the base class, getting the benefit of common functionality implemented while being able to override / expand upon functionality.

Approach 1 is likely quicker. Approach 2 is likely more proper, but should probably only be done if there's enough overlap between the functions in the 3 components.

Curious to hear everyone's thoughts.

P.S. Please label this `pr: Discuss`.

### LINKED ISSUE #946: Potentially Incorrect Usage of onChange with antd's Form
Upon reading AntDesign's documentation for using `Form`, I found the following note:
> After wrapped by getFieldDecorator, value(or other property defined by valuePropName) onChange(or other property defined by trigger) props will be added to form controls，the flow of form data will be handled by Form which will cause:
> 1. **You shouldn't use onChange to collect data**, but you still can listen to onChange(and so on) events.

Just to clarify, our usage of `Form`:
- Uses `getFieldDecorator`
- Uses `onChange` to collect data

I don't know the full history of this comment in `Editor.js`:
> // NOTE: antd doesn't update field value on Select before firing onChange
    // so we have to get value from event.

So I'm not clear if the author was aware of the note in the documentation or not. If this function was implemented with the knowledge of that documentation, then feel free to close the issue.

However, for the sake of this issue I'm going to operate under the assumption that it wasn't. If that's the case, it would explain why we had issues with collecting data from `onChange`.

In fact, in my fix for #924, I found that validators aren't invoked until *after* `onChange` has run, and when I triggered the validators from within `onChange`, I found that they were running against the previous data - i.e. I had just entered 6 tags, and the validator ran on the previous input which contained 5 tags, hence it did not fail.

So going with the assumption that we shouldn't be using `onChange` in this way, we should switch from using `onChange` to using their recommended function `onFieldsChange`. In theory, this should free us from our workaround functions like `onUpdate` and `getValues`.

If I'm completely wrong about this issue, please let me know what the story is and why we should in fact be using `onChange`.

### PR DESCRIPTION
**Pull request by Sekhmet**
Fixes #913 

Changes:
- [x] Add EditorInput
- [x] Add withEditor
- [x] Update Editor
- [x] Update CommentForm
- [x] Update EmbeddedCommentForm
- [x] Expose input as ref to allow focusing.

### CODE REVIEW

**Comment by bonustrack** [comment]
Copy paste an image does not seem to be working anymore. Can you check that @Sekhmet ?

**Comment by bonustrack** [comment]
The textarea feel too too big now, can you use the same height than before?
image
image

**Comment by jm90m** [comment]
Been going through the code, all looks fine to me, I was testing it a few days ago, and everything was also working fine 👍 , but for some reason now I can't login, anyways I guess once @bonustrack is done with his style inputs its good to merge

**Comment by Sekhmet** [comment]
@bonustrack not sure if you have seen, but size has been updated already.

**Pull request merged**
