### PR TITLE
Fix activity formatting on unfamiliar custom json operations (#1909)

### LINKED ISSUE #1909: Some custom json ops cause empty activity
#### Expected behavior

STEEM blockchain lets accounts to push any type of JSON into custom_json operations. Activity page should show the operation's details. 

Since it's impossible to pre-define the structure on this, visualization may be done via tables. (Or as a design decision, busy may ignore the unregistered CustomJSON operations.)

#### Actual behavior

Activity pages show the operation empty, fails to fill the row.

Example:

screen shot 2018-05-26 at 6 44 54 pm

See [related transaction](https://steemd.com/tx/f8f28a359f1d8d01eebef1d6f9cd9273df22ceb4). It happens any type pf custom json except follow/unfollow/ignore/reblog.

#### How to reproduce

Push a CustomJSON operation to the blockchain. It shouldn't follow the conventions on known custom jsons. (follow/unfollow, mute, etc.)

You will the see the activity page shows a blank entry.

For the reference, here is a python script to reproduce the issue:

```python
from steem import Steem
from steem.transactionbuilder import TransactionBuilder
from steembase import operations
s = Steem(nodes=["https://rpc.buildteam.io"],
          keys=["active_wif"])
account = "emrebeyler"
ops = [
    operations.CustomJson(**{
        "from": account,
        "id": "custom_id",
        "json": [
            'custom_action',
             {
                "custom_key": "custom_value",
            }
        ],
        "required_auths": [],
        "required_posting_auths": [account, ],
    }),
]
tb = TransactionBuilder()
tb.appendOps(ops)
tb.appendSigner(account, "posting")
tb.sign()
tb.broadcast()
```

* Browser/App version: Chrome Version 66.0.3359.181 (Official Build) (64-bit) on latest stable busy release
* Operating system: OSX Sierra

### PR DESCRIPTION
**Pull request by emre**
Fixes #1909 

### Changes

Current activity code checks for the operations is a [known operation (parsed)](https://github.com/busyorg/busy/blob/f0f5ae79d788c82e6801e1ed09aad1b1488e823f/src/client/activity/UserActionContents.js#L7) and if it's not a parsed property returns a generic table view.

While we parse some custom jsons (follow, unfollow, reblog, mute), we don't/can't have parsing support for all type of custom jsons since every account can push anything.

This is not a common thing in the blockchain but, recently, steemmonsters started using custom_jsons for their game. This created lots of custom jsons (both user side, and steemmonsters side) which creates empty items the activity feed.

Added a special check for custom jsons where the custom json ID is ```follow``` or not. (follow, unfollow, reblog, mute are a part of follow plugin in the blockchain consensus, so their custom json id is "follow") if it's follow, we behave like it's parsed property. Otherwise, fallback to generic table view.

### Test plan

* [ ] See [@steemmonsters' activity page](http://busy.org/@steemmonsters/activity) and look at how custom jsons are rendered.

### Demo 

**Before**

screen shot 2018-06-26 at 10 29 58 pm

**After**

screen shot 2018-06-26 at 10 29 40 pm

### CODE REVIEW

**Comment by Sekhmet** [comment]
Hey, current custom_ops stopped working (like reblogs):
https://busy-master-pr-2015.herokuapp.com/@hellosteem/activity
image

I feel like we should have some icon for custom_ops. I'm not sure which one to use, because for some reason iconfont.cn doesn't load for me. What do you think?

**Comment by emre** [comment]
Updated and rebased the commit - all custom jsons should be fine, now. :)

Regarding icons, will have a look.

**Comment by Sekhmet** [comment]
We changed default branch to `develop`. Can you update this PR to merge into `develop` whenever you are ready?

**Comment by emre** [comment]
Addressed the issues. 

Let's continue on this https://github.com/busyorg/busy/pull/2037.

**Pull request closed without merging**
