### PR TITLE
Migrate to webpack 4

### PR DESCRIPTION
**Pull request by yamadapc**
Updates dependencies and configuration to migrate to webpack 4. Needs testing.

### CODE REVIEW

**Comment by bonustrack** [comment]
For some reason the deployement in Heroku is not working: https://busy-master-pr-1616.herokuapp.com/

From the log i can see that the deployement was successfull but i dont see what made the app crash. I've just set Papertrail on Herorku for this PR, i will click "update branch" to trigger new deployement and see if there is more log.

**Comment by bonustrack** [comment]
Sorry i missed the `WIP` on this PR, you maybe aware about what's missing.

**Comment by yamadapc** [comment]
Hm... This should be good. Are there deployment logs @bonustrack ?

**Comment by jm90m** [comment]
This ready to be reviewed @yamadapc ?

**Comment by Sekhmet** [comment]
```
Mar 09 23:15:56 busy-master-pr-1616 heroku/web.1:  Starting process with command `pm2 startOrReload ecosystem.config.js --update-env && pm2 logs all` 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:                          ------------- 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:  __/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____ 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:   _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___ 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:    _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__ 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:     _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___ 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:      _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____ 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:       _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________ 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:        _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________ 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:         _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_ 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:          _\///______________\///______________\///__\///////////////__ 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:                            Community Edition 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:              Production Process Manager for Node.js applications 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:                       with a built-in Load Balancer. 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:                  Start and Daemonize any application: 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:                  $ pm2 start app.js 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:                  Load Balance 4 instances of api.js: 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:                  $ pm2 start api.js -i 4 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:                  Monitor in production: 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:                  $ pm2 monitor 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:                  Make pm2 auto-boot at server restart: 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:                  $ pm2 startup 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:                  To go further checkout: 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:                  http://pm2.io/ 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:                          ------------- 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:  [PM2] Spawning PM2 daemon with pm2_home=/app/.pm2 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:  [PM2] PM2 Successfully daemonized 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:  [PM2][WARN] Applications busy not running, starting... 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:  [PM2][ERROR] script not found : /app/busy.server.js 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:  ┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐ 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:  │ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │ 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:  └──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘ 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:   Use `pm2 show <id|name>` to get more details about an app 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:  [TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option) 
Mar 09 23:15:59 busy-master-pr-1616 app/web.1:  [PM2][ERROR] No file to stream for app [all], exiting. 
Mar 09 23:15:59 busy-master-pr-1616 heroku/web.1:  State changed from starting to crashed 
Mar 09 23:15:59 busy-master-pr-1616 heroku/web.1:  Process exited with status 1 
Mar 10 04:17:11 busy-master-pr-1616 heroku/router:  at=error code=H10 desc="App crashed" method=GET path="/" host=busy-master-pr-1616.herokuapp.com request_id=98b9e6e6-e1b7-4494-8dc1-b051b3aca4c4 fwd="77.32.244.2" dyno= connect= service= status=503 bytes= protocol=https 
Mar 10 04:17:14 busy-master-pr-1616 heroku/router:  at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=busy-master-pr-1616.herokuapp.com request_id=f1c82405-4ca1-4727-a6b4-d2cdcd565eb1 fwd="77.32.244.2" dyno= connect= service= status=503 bytes= protocol=https 
Mar 10 04:17:16 busy-master-pr-1616 heroku/router:  at=error code=H10 desc="App crashed" method=GET path="/" host=busy-master-pr-1616.herokuapp.com request_id=8fcfab49-49ea-410c-94d5-84a2ec5dbbcc fwd="77.32.244.2" dyno= connect= service= status=503 bytes= protocol=https 
Mar 10 04:17:17 busy-master-pr-1616 heroku/router:  at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=busy-master-pr-1616.herokuapp.com request_id=9120ad71-9371-4619-9cae-dc8340f52306 fwd="77.32.244.2" dyno= connect= service= status=503 bytes= protocol=https 
Mar 10 04:17:29 busy-master-pr-1616 heroku/router:  at=error code=H10 desc="App crashed" method=GET path="/" host=busy-master-pr-1616.herokuapp.com request_id=6c045f72-9ede-41d3-9ea3-730f8dfb5d4b fwd="77.32.244.2" dyno= connect= service= status=503 bytes= protocol=https 
Mar 10 04:17:31 busy-master-pr-1616 heroku/router:  at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=busy-master-pr-1616.herokuapp.com request_id=0f0623f5-9a72-4a4b-97cc-5eeb4bec662f fwd="77.32.244.2" dyno= connect= service= status=503 bytes= protocol=https 

```

**Comment by bonustrack** [comment]
@yamadapc did you have a chance to look about these deployment log? Would be nice to rollout this PR.

**Comment by yamadapc** [comment]
The deployment should work now

**Comment by bonustrack** [comment]
It seem that webpack 4 is breaking the layout or `antd` is not ready for it? Here is the deployement:
https://busy-master-pr-1616.herokuapp.com/
vs https://busy.org

**Comment by bonustrack** [comment]
Would be interesting to know if its something we can solve.

**Comment by yamadapc** [comment]
Hm... I hadn't noticed that. Maybe it's from `antd@3`

**Comment by jm90m** [comment]
@yamadapc it is from antd3 probably, but im not sure why the background-color for header is `#001529` instead of its normal color...

**Comment by bonustrack** [comment]
The app background also is wrong. Popup has some font broken etc...

**Comment by jm90m** [comment]
@bonustrack It might be because its not loading the override styles that we have for antd.

**Comment by bonustrack** [comment]
Right, it could be simple as that

**Comment by yamadapc** [comment]
I just tried with antd@2 and it's still broken

**Comment by jm90m** [comment]
Could it be related to here - https://github.com/ant-design/ant-design/issues/7850 ? @yamadapc @bonustrack

**Comment by jm90m** [comment]
It looks like you're going to have to override this - https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less#L209

If you go on production - busy.org and checkout the styles for the header `.ant-layout-header`
you'll see that there is a background override `background: 0 0;`

**Comment by bonustrack** [comment]
@yamadapc did you tried @jm90m recommendation? If not you may want @jm90m to take over the PR and see if there is something we can do, otherwise we will need to close this PR.

**Comment by bonustrack** [comment]
@jm90m can you take a look if you can find something to fix that issue, please dont spend too much time on this, if there is no obvious solution we will block this PR for now.

**Comment by jm90m** [comment]
yeah @bonustrack, I am not too sure, I updated the yarn.lock file, and I've been playing around with the config... This works fine locally, idk why its not working on production builds

**Comment by Sekhmet** [comment]
I updated our code to Webpack 4 here: https://github.com/busyorg/busy/commits/migrate-to-webpack-4

I don't think we should prioritize this, not every plugin is supported by webpack 4, documentation is mediocre and there is a bug that causes server to build 10 times longer. There are not lots of benefits to upgrade.

**Comment by bonustrack** [comment]
I'm closing this PR but we can keep the branch alive waiting for webpack 4 to be more mature and better handled with plugins.

**Pull request closed without merging**
